FROM python:3.8

WORKDIR /app

ADD testSet.zip testSet.zip

RUN unzip testSet.zip

RUN pip install numpy requests

ADD load_generator.py load_generator.py

ENTRYPOINT [ "python", "load_generator.py" ]
